name: SNISRelease

on: workflow_dispatch

 assets:
    name: upload assets
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write

    steps:
      - uses: actions/checkout@v3
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload releasetag Space_Nerds_in_Space-x86_64.AppImage
