name: SNISBuilder

on: workflow_dispatch
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    #runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    #container: centos:7

    steps:
    - uses: actions/checkout@v4

    - name: Configure MakeIt
      run: |      
        sudo add-apt-repository universe
        sudo apt install libfuse2t64
        sudo apt-get -y install build-essential portaudio19-dev libpng-dev libvorbis-dev libsdl2-dev libsdl2-2.0-0 liblua5.2-dev libglew-dev libttspico-utils sox espeak alsa-utils
        git clone --depth 1 https://github.com/smcameron/space-nerds-in-space.git
        SnisGitDir='space-nerds-in-space'
        cd $SnisGitDir
        make
        make update-assets
        cd ..
        AppDir='SpaceNerdsInSpaceDir'
        mkdir -p $AppDir/usr/bin
        mkdir -p $AppDir/usr/lib
        cp -r $SnisGitDir/bin $AppDir/usr/bin
        cp -r $SnisGitDir/*.png $AppDir/usr/bin
        cp $SnisGitDir/snis_launcher $AppDir/usr/bin
        cp -r $SnisGitDir/share $AppDir/usr/bin
        ldd $AppDir/usr/bin/bin/snis_client | awk -v AppDir=$AppDir  'NF == 4 { echo system("cp " $3 " " AppDir "/usr/lib/") }'
        #rm $AppDir/usr/lib/libc.*
        git clone --depth 1 https://github.com/vpelss/Space-Nerds-In-Space-Appimage.git
        SnisAppImageToolsDir='Space-Nerds-In-Space-Appimage'
        cp $SnisAppImageToolsDir/AppRun SpaceNerdsInSpaceDir
        cp $SnisAppImageToolsDir/icon.png SpaceNerdsInSpaceDir
        cp $SnisAppImageToolsDir/snis.desktop SpaceNerdsInSpaceDir
        #set permissions
        chmod +x $AppDir/AppRun 
        chmod +x $AppDir/usr/bin/snis_launcher
        chmod +x $AppDir/usr/bin/bin/*
        chmod +x $AppDir/snis.desktop

    - name: Build
      # Build your program with the given configuration
      run: |
        AppDir='SpaceNerdsInSpaceDir'
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        ARCH=x86_64 ./linuxdeploy-x86_64.AppImage --appdir $AppDir --output appimage
        chmod 777 Space_Nerds_in_Space-x86_64.AppImage
        printf '0' |./Space_Nerds_in_Space-x86_64.AppImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Space_Nerds_in_Space-x86_64.AppImage 
        path: Space_Nerds_in_Space-x86_64.AppImage 
