name: SNISBuilder

on: workflow_dispatch
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04
    #container: centos:7

    steps:
    - uses: actions/checkout@v4

    - name: Configure MakeIt
      run: |      
        sudo apt-get -y install build-essential portaudio19-dev libpng-dev libvorbis-dev libsdl2-dev libsdl2-2.0-0 liblua5.2-dev libglew-dev libttspico-utils sox espeak alsa-utils
        git clone https://github.com/smcameron/space-nerds-in-space.git
        cd space-nerds-in-space
        make
        make update-assets
        cd ../
        mkdir -p SpaceNerdsInSpaceDir/usr/bin
        mkdir -p SpaceNerdsInSpaceDir/usr/lib
        cp -r space-nerds-in-space/bin SpaceNerdsInSpaceDir/usr/bin
        cp -r space-nerds-in-space/*.png SpaceNerdsInSpaceDir/usr/bin
        cp space-nerds-in-space/snis_launcher SpaceNerdsInSpaceDir/usr/bin
        cp -r space-nerds-in-space/share SpaceNerdsInSpaceDir/usr/bin
        git clone --depth 1 https://github.com/vpelss/Space-Nerds-In-Space-Appimage.git
        cp Space-Nerds-In-Space-Appimage/AppRun SpaceNerdsInSpaceDir
        cp Space-Nerds-In-Space-Appimage/icon.png SpaceNerdsInSpaceDir
        cp Space-Nerds-In-Space-Appimage/snis.desktop SpaceNerdsInSpaceDir
        #set permissions
        chmod +x SpaceNerdsInSpaceDir/AppRun 
        chmod +x SpaceNerdsInSpaceDir/usr/bin/snis_launcher
        chmod +x SpaceNerdsInSpaceDir/usr/bin/bin/*
        chmod +x SpaceNerdsInSpaceDir/snis.desktop
        ldd SpaceNerdsInSpaceDir/usr/bin/bin/snis_client | awk 'NF == 4 { system("cp " $3 " SpaceNerdsInSpaceDir/usr/lib/") }'
        ls
        ls SpaceNerdsInSpaceDir/usr/lib/
        echo "::stop-commands::$stopMarker"

    - name: Build
      # Build your program with the given configuration
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        #run linuxdeploy and fix up generate an AppDir (add lib) and build AppImage 
        ARCH=x86_64 ./linuxdeploy-x86_64.AppImage -v 0 --appdir SpaceNerdsInSpaceDir --output appimage
        chmod 777 Space_Nerds_in_Space-x86_64.AppImage
        #run it
        printf '0' |./Space_Nerds_in_Space-x86_64.AppImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Space_Nerds_in_Space-x86_64.AppImage 
        path: Space_Nerds_in_Space-x86_64.AppImage 
